environment_name: dev

# Our module for creating caches prefixes all the variables with cache, to enable
# us to set generic variables in Terragrunt that are descriptive and don't
# clash with other resources such as databases
cache_num_nodes: 1
cache_engine: redis
cache_node_type: cache.t3.large
cache_engine_version: 6

# Similar to the above, our database module takes variables prefixed with
# "database" so they don't clash with other variables
database_allocated_storage: 10
database_engine: mysql
database_engine_version: 5.7
database_instance_class: db.t3.large
database_storage_type: gp2
